cp ./app/assets/android/appicon_.png ./app/assets/android/appicon.png
cp ./app/assets/android/default_.png ./app/assets/android/default.png
cp ./app/assets/android/images/res-long-land-hdpi/default_.png ./app/assets/android/images/res-long-land-hdpi/default.png
cp ./app/assets/android/images/res-long-land-ldpi/default_.png ./app/assets/android/images/res-long-land-ldpi/default.png
cp ./app/assets/android/images/res-long-port-hdpi/default_.png ./app/assets/android/images/res-long-port-hdpi/default.png
cp ./app/assets/android/images/res-long-port-ldpi/default_.png ./app/assets/android/images/res-long-port-ldpi/default.png
cp ./app/assets/android/images/res-notlong-land-hdpi/default_.png ./app/assets/android/images/res-notlong-land-hdpi/default.png
cp ./app/assets/android/images/res-notlong-land-ldpi/default_.png ./app/assets/android/images/res-notlong-land-ldpi/default.png
cp ./app/assets/android/images/res-notlong-land-mdpi/default_.png ./app/assets/android/images/res-notlong-land-mdpi/default.png
cp ./app/assets/android/images/res-notlong-port-hdpi/default_.png ./app/assets/android/images/res-notlong-port-hdpi/default.png
cp ./app/assets/android/images/res-notlong-port-ldpi/default_.png ./app/assets/android/images/res-notlong-port-ldpi/default.png
cp ./app/assets/android/images/res-notlong-port-mdpi/default_.png ./app/assets/android/images/res-notlong-port-mdpi/default.png
cp ./app/assets/images/login_.png ./app/assets/images/login.png
cp ./app/assets/iphone/appicon-60_.png ./app/assets/iphone/appicon-60.png
cp ./app/assets/iphone/appicon-60@2x_.png ./app/assets/iphone/appicon-60@2x.png
cp ./app/assets/iphone/appicon-60@3x_.png ./app/assets/iphone/appicon-60@3x.png
cp ./app/assets/iphone/appicon-72_.png ./app/assets/iphone/appicon-72.png
cp ./app/assets/iphone/appicon-72@2x_.png ./app/assets/iphone/appicon-72@2x.png
cp ./app/assets/iphone/appicon-Small-50_.png ./app/assets/iphone/appicon-Small-50.png
cp ./app/assets/iphone/appicon-Small_.png ./app/assets/iphone/appicon-Small.png
cp ./app/assets/iphone/appicon-Small@2x_.png ./app/assets/iphone/appicon-Small@2x.png
cp ./app/assets/iphone/appicon_.png ./app/assets/iphone/appicon.png
cp ./app/assets/iphone/appicon@2x_.png ./app/assets/iphone/appicon@2x.png
cp ./app/assets/iphone/Default-568h@2x_.png ./app/assets/iphone/Default-568h@2x.png
cp ./app/assets/iphone/Default-667h@2x_.png ./app/assets/iphone/Default-667h@2x.png
cp ./app/assets/iphone/Default-Landscape-736h@3x_.png ./app/assets/iphone/Default-Landscape-736h@3x.png
cp ./app/assets/iphone/Default-Landscape_.png ./app/assets/iphone/Default-Landscape.png
cp ./app/assets/iphone/Default-Landscape@2x_.png ./app/assets/iphone/Default-Landscape@2x.png
cp ./app/assets/iphone/Default-Portrait-667h@2x_.png ./app/assets/iphone/Default-Portrait-667h@2x.png
cp ./app/assets/iphone/Default-Portrait-736h@3x_.png ./app/assets/iphone/Default-Portrait-736h@3x.png
cp ./app/assets/iphone/Default-Portrait_.png ./app/assets/iphone/Default-Portrait.png
cp ./app/assets/iphone/Default-Portrait@2x_.png ./app/assets/iphone/Default-Portrait@2x.png
cp ./app/assets/iphone/Default_.png ./app/assets/iphone/Default.png
cp ./app/assets/iphone/Default@2x_.png ./app/assets/iphone/Default@2x.png
cp ./app/assets/iphone/iTunesArtwork_.png ./app/assets/iphone/iTunesArtwork.png
cp ./build/iphone/DefaultIcon_.png ./build/iphone/DefaultIcon.png
cp ./DefaultIcon_.png ./DefaultIcon.png
cp ./DefaultIcon-ios_.png ./DefaultIcon-ios.png
cp ./iTunesConnect_.png ./iTunesConnect.png
cp ./MarketplaceArtwork_.png ./MarketplaceArtwork.png
cp ./PlayFeatureGraphic_.png ./PlayFeatureGraphic.png
cp ./Resources/iphone/appicon-60_.png ./Resources/iphone/appicon-60.png
cp ./Resources/iphone/appicon-60@2x_.png ./Resources/iphone/appicon-60@2x.png
cp ./Resources/iphone/appicon-60@3x_.png ./Resources/iphone/appicon-60@3x.png
cp ./Resources/iphone/appicon-72_.png ./Resources/iphone/appicon-72.png
cp ./Resources/iphone/appicon-72@2x_.png ./Resources/iphone/appicon-72@2x.png
cp ./Resources/iphone/appicon-Small-50_.png ./Resources/iphone/appicon-Small-50.png
cp ./Resources/iphone/appicon-Small_.png ./Resources/iphone/appicon-Small.png
cp ./Resources/iphone/appicon-Small@2x_.png ./Resources/iphone/appicon-Small@2x.png
cp ./Resources/iphone/appicon_.png ./Resources/iphone/appicon.png
cp ./Resources/iphone/appicon@2x_.png ./Resources/iphone/appicon@2x.png
cp ./Resources/iphone/Default-568h@2x_.png ./Resources/iphone/Default-568h@2x.png
cp ./Resources/iphone/Default-667h@2x_.png ./Resources/iphone/Default-667h@2x.png
cp ./Resources/iphone/Default-Landscape-736h@3x_.png ./Resources/iphone/Default-Landscape-736h@3x.png
cp ./Resources/iphone/Default-Landscape_.png ./Resources/iphone/Default-Landscape.png
cp ./Resources/iphone/Default-Landscape@2x_.png ./Resources/iphone/Default-Landscape@2x.png
cp ./Resources/iphone/Default-Portrait-667h@2x_.png ./Resources/iphone/Default-Portrait-667h@2x.png
cp ./Resources/iphone/Default-Portrait-736h@3x_.png ./Resources/iphone/Default-Portrait-736h@3x.png
cp ./Resources/iphone/Default-Portrait_.png ./Resources/iphone/Default-Portrait.png
cp ./Resources/iphone/Default-Portrait@2x_.png ./Resources/iphone/Default-Portrait@2x.png
cp ./Resources/iphone/Default_.png ./Resources/iphone/Default.png
cp ./Resources/iphone/Default@2x_.png ./Resources/iphone/Default@2x.png
cp ./Resources/iphone/images/go-next_.png ./Resources/iphone/images/go-next.png
cp ./Resources/iphone/images/login_.png ./Resources/iphone/images/login.png
cp ./Resources/iphone/iTunesArtwork_.png ./Resources/iphone/iTunesArtwork.png
